---
- hosts: localhost
  vars_files: 
  - vars/k8s_vars.yaml
  roles:
    - name: makecerts
      when: run_makecerts


- hosts: all
  vars_files:
  - vars/k8s_vars.yaml 
  roles:
   - name: bootstrap
     when: run_bootstrap

- hosts: etcd
  gather_facts: True
  vars_files:
  - vars/k8s_vars.yaml 
  roles:
   - name: etcd
     when: run_etcd

- hosts: masters
  gather_facts: True
  vars_files:
  - vars/k8s_vars.yaml 
  roles:
   - name: master_install
     when: run_master
#  
#  
#- hosts: nodes
#  gather_facts: False
#  vars_files:
#  - vars/k8s_vars.yaml
#
#  roles:
#    - node_install
#
#- hosts: localhost
##  gather_facts: False
#  vars_files:
#  - vars/k8s_vars.yaml
#
#  roles:
#    - node_config
#
