- hosts: localhost

  roles:
    - makecerts


- hosts: masters
  gather_facts: False
  vars_files: 
  - vars/k8s_vars.yaml

  roles:
    - bootstrap


- hosts: masters
  gather_facts: True
  vars_files:
  - vars/k8s_vars.yaml 

  roles:
   - master_install
  
  
- hosts: nodes
  gather_facts: False
  vars_files:
  - vars/k8s_vars.yaml

  roles:
    - node_install

- hosts: localhost
#  gather_facts: False
  vars_files:
  - vars/k8s_vars.yaml

  roles:
    - node_config

