---
all:
  vars:
    student_number:             "275"
    ansible_user:               student
    ansible_python_interpreter: /usr/bin/python3
    class: "k8s"
  children:  
    masters:
      hosts:
        master1:
          ansible_host: "{{ class }}-{{ student_number }}-master-01.localdomain"
        master2:
          ansible_host: "{{ class }}-{{ student_number }}-master-02.localdomain"
        master3:
          ansible_host: "{{ class }}-{{ student_number }}-master-03.localdomain"  
      vars: 
        public_ip: "{{ lookup('dig', ansible_host) }}"
        public_fqdn: "{{ ansible_host }}"
        public_hostname: "{{ ansible_hostname }}"
    etcd:
        children:
            masters  
    nodes:
      hosts:
        node1:
          ansible_host: "{{ class }}-{{ student_number }}-node-01.localdomain" 
          cni_host_subnet: "192.168.1.0/24"
        node2:
          ansible_host: "{{ class }}-{{ student_number }}-node-02.localdomain" 
          cni_host_subnet: "192.168.2.0/24"
        node3:
          ansible_host: "{{ class }}-{{ student_number }}-node-03.localdomain"
          cni_host_subnet: "192.168.3.0/24"
      vars: 
        public_ip: "{{ lookup('dig', ansible_host) }}"
        public_fqdn: "{{ ansible_host }}"
        public_hostname: "{{ ansible_hostname }}"
