---
all:
  vars:
    ansible_user:               student
    ansible_python_interpreter: /usr/bin/python3
  children:  
    masters:
      hosts:
        master1:
          ansible_host: master-01
        master2:
          ansible_host: master-02
        master3:
          ansible_host: master-03
      vars: 
        public_ip: "{{ lookup('dig', ansible_host) }}"
        public_fqdn: "{{ ansible_host }}"
        public_hostname: "{{ ansible_hostname }}"
    etcd:
        children:
            masters  
    nodes:
      hosts:
        node1:
          ansible_host: node-01
          cni_host_subnet: "192.168.1.0/24"
        node2:
          ansible_host: node-02
          cni_host_subnet: "192.168.2.0/24"
        node3:
          ansible_host: node-03
          cni_host_subnet: "192.168.3.0/24"
      vars: 
        public_ip: "{{ lookup('dig', ansible_host) }}"
        public_fqdn: "{{ ansible_host }}"
        public_hostname: "{{ ansible_hostname }}"
