---
- hosts: all
  roles:
   - name: bootstrap
     when: run_bootstrap

- hosts: localhost
  roles:
   - name: make_certs
     when: run_makecerts
   - name: node_kube_config
     when: run_nodeconfig
   - name: localhost_config
     when: run_localconfig
   - name: calico
     when: run_calico

- hosts: etcd
  gather_facts: True
  roles:
   - name: etcd
     when: run_etcd

- hosts: masters
  gather_facts: True
  roles:
   - name: master_install
     when: run_master

- hosts: localhost,nodes
  gather_facts: False
  roles:
   - name: nginx_localhost_load_balancer
     when: run_nginx_lb
  
- hosts: nodes
  gather_facts: False
  roles:
   - name: node_install
     when: run_nodes
