
#TODO: these node-routes are hard coded, on a day far far from now, MAYBE templatized and smartly created
#TODO THIS IS BROKEN GIVEN THE IP's are not correct for the nodes
#TODO make the same thing as the next task but as a template (reboot persistance of routes) 
#- name: Create the pod-routes file for each node. Sets routes to get outbound connections from the calico network
#  copy: 
#    src: "{{  role_path  }}/files/node-routes"
#    dest: "/etc/network/if-up.d/node-routes"
#    mode: "0775"
#  become: yes

- name: configure routes to nodes (pod routes)
  command: "ip route add {{ hostvars[item].cni_host_subnet }} via {{ hostvars[item].public_ip }}"
  loop: "{{ groups['nodes'] }}"
  become: yes
  register: cmd_result
  failed_when:
  - "'answers: File exists' not in cmd_result.stderr"
  - "cmd_result.rc != 0"

- name: bchd-k8s-config - setup localhost loadbalancer for kubectl (as admin)
  shell: kubectl config set-cluster {{ cluster_name }} \
         --certificate-authority={{ ca_pem_file }}  \
         --embed-certs=true \
         --server={{ localhost_lb_apiserver_address }}

- name: bchd-k8s-config - setup creds for admin user
  shell: kubectl config set-credentials admin \ 
         --client-certificate={{ admin_pem_file }} \
         --client-key={{ admin_key_file }} \ 

- name: bchd-k8s-config - setup context for the admin user
  shell: kubectl config set-context {{ cluster_name }} 
         --cluster={{ cluster_name }} \
         --user=admin

- name: bchd-k8s-config - setup use-context for the admin user
  shell: kubectl config use-context {{ cluster_name }}

