#``````````````````````````````````````````````````````````
# Install fping
#``````````````````````````````````````````````````````````

 - name: install fping for checking if nodes are alive
   apt:
    name: fping
    state: present
   become: yes


#``````````````````````````````````````````````````````````
# Setup nginx
#``````````````````````````````````````````````````````````
#
# - name: Install nginx for ??
#   apt:
#    name: nginx
#    state: present
#   become: yes
#
# - name: Create the config file for nginx
#   template:
#     src: "{{ role_path }}/templates/nginx.conf.j2"
#     dest: "/etc/nginx/nginx.conf"
#   become: yes
#
# - name: Start the nginx service
#   systemd:
#     name: nginx
#     daemon_reload: yes
#     state: started
#     enabled: yes
#   become: yes


#``````````````````````````````````````````````````````````
# Locally configure kubernetes #TODO: is the below necessary, to even have the admin.pem or the admin-key.pem created?
#``````````````````````````````````````````````````````````

 - name: Verify the cluster is set on the beachhead control machine
   shell: kubectl config set-cluster kubernetes-the-alta3-way --certificate-authority=/var/lib/kubernetes/ca.pem --embed-certs=true --server=https://127.0.0.1:6443

 - name: Verify the credentials are set on the beachhead control machine
   shell: kubectl config set-credentials admin --client-certificate=/home/student/admin.pem --client-key=/home/student/admin-key.pem

 - name: Verify the context is set for the admin user
   shell: kubectl config set-context kubernetes-the-alta3-way --cluster=kubernetes-the-alta3-way --user=admin

 - name: Use the context for the config file
   shell: kubectl config use-context kubernetes-the-alta3-way

