---
- name: Create cert directories
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ cert_dir }}"
  - "{{ config_dir }}"
  - "{{ csr_dir }}"

- name: Install dependencies with get_url -> cfssl, cfssljson, kubectl
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
  - { url: "{{ cfssl_url }}", 
      dest: /usr/local/bin/cfssl, 
      mode: '0755' }
  - { url: "{{ cfssljson_url }}", 
      dest: /usr/local/bin/cfssljson, 
      mode: '0755' }
  - { url: "{{ kubectl.url }}",
      dest: "{{ kubectl.path }}",
      mode: '0755' }
  become: True

# Deploy certificate configuration data 
- name: Deploy certificate generation configuration files
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
   - src: "{{ role_path }}/templates/ca-config.json.j2"
     dest: "{{ ca_config_file }}"
   - src: "{{ role_path }}/templates/ca-csr.json.j2"
     dest: "{{ ca_csr_config_file }}"
   - src: "{{ role_path }}/templates/admin-csr.json.j2"
     dest: "{{ admin_csr_config_file }}"
   - src: "{{ role_path }}/templates/kube-controller-manager-csr.json.j2"
     dest: "{{ kube_controller_manager_csr_config_file }}"
   - src: "{{ role_path }}/templates/kube-proxy-csr.json.j2"
     dest: "{{ kube_proxy_csr_config_file }}"
   - src: "{{ role_path }}/templates/kube-scheduler-csr.json.j2"
     dest: "{{ kube_scheduler_csr_config_file }}"
   - src: "{{ role_path }}/templates/kubernetes-csr.json.j2"
     dest: "{{ k8s_csr_config_file }}"
   - src: "{{ role_path }}/templates/kube-service-account-csr.json.j2"
     dest: "{{ kube_service_account_csr_config_file }}"
   - src: "{{ role_path }}/templates/kube-registry-web-csr.json.j2"
     dest: "{{ kube_registry_web_csr_config_file }}"

- name: Generate misc service configuration templates
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - src: "{{ role_path }}/templates/kube-scheduler.yaml.j2"
    dest: "{{ kube_scheduler_config_file }}"

- name: Generate the certificate config file for nodes (file same on all nodes)
  template:
    src: "{{ role_path }}/templates/node-csr.json.j2" 
    dest: "{{ csr_dir }}/{{ public_fqdn }}-csr.json"
  vars:
    public_fqdn: "{{ hostvars[item]['public_fqdn'] }}"
  loop: "{{ groups['nodes'] }}"
       
- name: Generate a self-signed CA cert and private key for the k8s cloud
  shell: "cfssl gencert -initca {{ ca_csr_config_file }} | cfssljson -bare ca"
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ ca_pem_file }}" # also ca-key.pem, ca.csr

- name: Create crt version of the ca.pem cert file
  shell: "openssl x509 -in {{ ca_pem_file }} -inform PEM -out {{ ca_crt_file }}"
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ ca_crt_file }}"

- name: Generate Certificate and private key for k8s API server and etcd
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -hostname={{ apiserver_cluster_ip }},{{ master_ips_csv }},{{ master_fqdn_csv }},127.0.0.1,kubernetes.default \
         -profile=kubernetes \
         {{ k8s_csr_config_file }} | cfssljson -bare kubernetes
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ k8s_pem_file }}" # also kubernetes.csr kubernetes-key.pem

- name: Generate admin certificates 
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -profile=kubernetes \
         {{ admin_csr_config_file }} | cfssljson -bare admin 
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ admin_pem_file }}" # also admin.csr admin-key.pem

- name: Generate kube-controller-manager client cert and private key 
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -profile=kubernetes \
         {{ kube_controller_manager_csr_config_file }} | cfssljson -bare kube-controller-manager
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ kube_controller_manager_pem_file }}" # also kube-controller-manager.csr kube-controller-manager-key.pem

- name: Generate kube-proxy client cert and private key 
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -profile=kubernetes \
         {{ kube_proxy_csr_config_file }} | cfssljson -bare kube-proxy
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ kube_proxy_pem_file }}" # also kube-proxy.csr kube-proxy-key.pem

- name: Generate kube-scheduler client cert and private key 
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -profile=kubernetes \
         {{ kube_scheduler_csr_config_file }} | cfssljson -bare kube-scheduler
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ kube_scheduler_pem_file }}" # also kube-scheduler.csr kube-scheduler-key.pem

- name: Generate service-account client cert and private key 
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -profile=kubernetes \
         {{ kube_service_account_csr_config_file }} | cfssljson -bare service-account
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ kube_service_account_pem_file }}" # also kube-service-account.csr kube-service-account-key.pem

- name: Generate registry web cert and private key 
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -profile=kubernetes \
         {{ kube_registry_web_csr_config_file }} | cfssljson -bare registry-web
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ kube_registry_web_pem_file }}" # also .csr .pem

- name: Generate the specific certificate and Private key for each node when it does not already exist
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -hostname={{ hostname }},{{ public_ip }},{{ public_fqdn }},{{ public_hostname }} \
         -profile=kubernetes {{ csr_dir }}/{{ public_fqdn }}-csr.json | cfssljson -bare {{ public_fqdn }}
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ cert_dir }}/{{ hostvars[item]['public_fqdn'] }}.pem"
  vars:
    public_fqdn: "{{ hostvars[item]['public_fqdn'] }}"
    public_ip: "{{ hostvars[item]['public_ip'] }}"
    public_hostname: "{{ hostvars[item]['public_hostname'] }}"
    hostname: "{{ hostvars[item].inventory_hostname }}"
  loop: "{{ groups['nodes'] }}"

- name: Discover if encryption config has already been generated
  stat: 
    path: "{{ encryption_config_file }}"
  register: ecf

- name: Generate an encryption key 
  shell: head -c 32 /dev/urandom | base64
  args:
    creates: "{{ encryption_config_file }}"
  register: encryption_key # used in template file
  when: ecf.stat.exists == False

- name: Generate the encryption config file
  template: 
    src: "{{ role_path }}/templates/encryption-config.yaml.j2"
    dest: "{{ encryption_config_file }}"
  when: ecf.stat.exists == False

