
  - name: Create directories on masters
    file:
      path: {{ item }}
      state: directory
    with_items:
    - "/etc/etcd"
    - "/var/lib/etcd"
    - "/var/lib/kubernetes"

  - name: Copy Certs and Config to Masters
    file:
      src: {{ item.source }}
      dest: {{ item.dest }}
    with_items:
    - { source: /var/lib/kubernetes/encryption-config.yaml, dest: /home/student/encryption-config.yaml }
    - { source: /var/lib/kubernetes/ca.pem, dest: /home/student/ca.pem }
    - { source: /var/lib/kubernetes/ca-key.pem, dest: /home/student/ca-key.pem } 
    - { source: /var/lib/kubernetes/kubernetes.pem, dest: /home/student/kubernetes.pem }
    - { source: /var/lib/kubernetes/kubernetes-key.pem, dest: /home/student/kubernetes-key.pem }

  - name: Copy Certs and Config to Masters etcd
    file:
      src: {{ item.source }}
      dest: {{ item.dest }}
    with_items:
    - { source: /var/lib/kubernetes/kubernetes.pem, dest: /etc/etcd/kubernetes.pem }
    - { source: /var/lib/kubernetes/kubernetes-key.pem, dest: /etc/etcd/kubernetes-key.pem }
    become: true

  - name: Download the etcd binaries on each master
    get_url:
      url: {{ item.url }}
      dest: {{ item.dest }}
    with_items:
    - { url: "https://github.com/coreos/etcd/releases/download/v3.2.11/etcd-v3.2.11-linux-amd64.tar.gz", dest: /home/student }
    - { url: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-apiserver", dest: /home/student } 
    - { url: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-controller-manager", dest: /home/student } 
    - { url: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-scheduler", dest: /home/student }
    - { url: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl", dest: /home/student }
        
  - name: Unpack the etcd binaries on each master
    unarchive:
      src: /home/student/etcd-v3.2.11-linux-amd64.tar.gz
      dest: /usr/local/bin
      
  - name: Add execute to to the kube
    file:
      path: {{ item.path }}
      mode: {{ item.mode }}
    with_items:
    - { path: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-apiserver", mode: u+x }
    - { path: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-controller-manager", mode: u+x } 
    - { path: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-scheduler", mode: u+x } 
    - { path: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl", mode: u+x } 
  
  - name: Move kube commands to local path # not sure if these should just be moved or what the reason would be to do so.
    copy:
     src: {{ item.source }}
     dest: {{ item.dest }}
    with_items:
    - { source: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-apiserver", dest: /usr/local/bin } 
    - { source: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-controller-manager", dest: /usr/local/bin } 
    - { source: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-scheduler", dest: /usr/local/bin }
    - { source: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl", dest: /usr/local/bin }   
    
  - name: Move certs to /var/lib/kubernetes # can the be a command task mv with_items? not sure if these should just be moved or what the reason would be to do so. seems redundant.
    copy:
     src: {{ item.source }}
     dest: {{ item.dest }}
    with_items:
    - { source: /home/student/ca.pem, dest: /var/lib/kubernetes } 
    - { source: /home/student/ca-key.pem, dest: /var/lib/kubernetes } 
    - { source: /home/student/kubernetes-key.pem, dest: /var/lib/kubernetes } 
    - { source: /home/student/encryption-config.yml, dest: /var/lib/kubernetes } 
    
####How do I get that jinja template to run with/against the playbook?
    {{ root_path }}/files  /templates jinja2
    or template module
   
   ####
    - name: user env - desktop customizations templates
       template:
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
         owner: "{{ student_user }}"
       become: yes
       tags: user_env
       with_items:
       - { src: "{{ role_path }}/templates/desktop-items-0.conf", dest: "/home/{{ student_user }}/.config/pcmanfm/LXDE/desktop-items-0.conf" }
       - { src: "{{ role_path }}/templates/lxde-panel", dest: "/home/{{ student_user }}/.config/lxpanel/LXDE/panels/panel" }
       - { src: "{{ role_path }}/templates/firefox.desktop.j2", dest: "/usr/share/applications/firefox.desktop" }
   
   ####

  - name: Move the services to /etc/systemd/system
    shell: mv kube-apiserver.service kube-scheduler.service kube-controller-manager.service /etc/systemd/system/
    args: 
      chdir: /home/student
    become: yes
    
  - name: Reload the daemon for the services
    shell: systemctl daemon-reload
    become: yes

  - name: Enable the services
    shell: systemctl enable kube-apiserver kube-controller-manager kube-scheduler
    become: yes

  - name: Start the API server
    shell: systemctl start kube-apiserver kube-controller-manager kube-scheduler
    become: yes
