#-------------------------------------------------------------------------------------
# Update /etc/hosts to reflect the renaming of controller to master and worker to node
#------------------------------------------------------------------------------------

  - name: Update /etc/hosts on all masters
    template: 
      src: "{{ role_path }}/templates/hosts.j2"
      dest: /etc/hosts
    become: yes    




#-------------------------------------------------------------------------
# Finish moving the certs we created on beachhead into the masters.

  - name: Create directories on masters
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - "/etc/etcd"
    - "/var/lib/etcd"
    - "/var/lib/kubernetes"
    become: yes

  - name: Copy Certs and Config to Masters
    copy:
      src: '{{ item.source }}'
      dest: '{{ item.dest }}'
    with_items:
    - { source: /var/lib/kubernetes/encryption-config.yaml, dest: /home/student/encryption-config.yaml }
    - { source: /var/lib/kubernetes/ca.pem, dest: /etc/etcd/ca.pem }
    - { source: /var/lib/kubernetes/ca-key.pem, dest: /home/student/ca-key.pem } 
    - { source: /var/lib/kubernetes/kubernetes.pem, dest: /etc/etcd/kubernetes.pem }
    - { source: /var/lib/kubernetes/kubernetes-key.pem, dest: /etc/etcd/kubernetes-key.pem }
    become: yes

#  - name: Copy Certs and Config to Masters etcd
#    copy:
#      src: "{{ item.source }}"
#      dest: "{{ item.dest }}"
#    with_items:
#    - { source: /var/lib/kubernetes/kubernetes.pem, dest: /etc/etcd/kubernetes.pem }
#    - { source: /var/lib/kubernetes/kubernetes-key.pem, dest: /etc/etcd/kubernetes-key.pem }
#    become: yes
#
#-------------------------------------------
# This is bootstrapping ETCD





  - name: Download the etcd binary on each master
    get_url:
      url: "https://github.com/coreos/etcd/releases/download/v3.2.11/etcd-v3.2.11-linux-amd64.tar.gz"
      dest: /home/student/etcd-v3.2.11-linux-amd64.tar.gz
      mode: '0664'
    become: yes

  - name: Unpack the etcd binaries on each master
    unarchive:
      remote_src: yes
      src: /home/student/etcd-v3.2.11-linux-amd64.tar.gz
      dest: /usr/local/bin
    become: yes

  - name: Push etcd service config
    template: 
      src: "{{ role_path }}/templates/etcd.service.j2"
      dest: /etc/systemd/system/etcd.service 
    become: yes    

  - name: Reload systemd manager
    command: systemctl daemon-reload
    become: yes
    
  - name: Reload the daemon for the services
    systemd: 
      name: etcd.service 
      enabled: yes
      state: restarted
    become: yes
 







#----------------------------------------------------------------------------------------------------------
# BOOTSTRAPPING KUBERNETES 
# ---------------------------------------------------------------------------------------------------------   


  - name: Move certs to /var/lib/kubernetes to support kubernetes API server
    copy:
      src: "{{ item.source }}"
      dest: "{{ item.dest }}"
    with_items:
    - { source: /var/lib/kubernetes/ca.pem, dest: /var/lib/kubernetes/ca.pem } 
    - { source: /var/lib/kubernetes/ca-key.pem, dest: /var/lib/kubernetes/ca-key.pem } 
    - { source: /var/lib/kubernetes/kubernetes-key.pem, dest: /var/lib/kubernetes/kubernetes-key.pem } 
    - { source: /var/lib/kubernetes/encryption-config.yaml, dest: /var/lib/kubernetes/encryption-config.yaml } 
    become: yes 


# API Server Install

  - name: Download the Kubernetes  APIServer binary
    get_url:
      url:  "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-apiserver"
      dest: /usr/local/bin/kube-apiserver
      mode: +x 
    become: yes

  - name: Push the config file for the API Server
    template:
      src: "{{ role_path }}/templates/kube-apiserver.service.j2"
      dest: /etc/systemd/system/kube-apiserver.service
    become: yes 


# Manager Install

  - name: Download the Kubernetes Manager 
    get_url:
      url: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-controller-manager" 
      dest: /usr/local/bin/kube-controller-manager
      mode: +x 
    become: yes

  - name: Configure the Kubernetes master manager service
    template:
      src: "{{ role_path }}/templates/kube-controller-manager.service.j2"
      dest: /etc/systemd/system/kube-controller-manager.service
    become: yes


# Scheduler Install

  - name: Download Kubernetes Scheduler 
    get_url:
      url: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kube-scheduler"
      dest: /usr/local/bin/kube-scheduler 
      mode: +x
    become: yes

  - name: Configure the Kubernetes master scheduler
    copy:
      src: "{{ role_path }}/files/kube-scheduler.service"
      dest: /etc/systemd/system/kube-scheduler.service
    become: yes 


# Install Kubectl

  - name: Download Kubernetes kubectl 
    get_url:
      url: "https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl"
      dest: /usr/local/bin/kubectl
      mode: +x 
    become: yes


# Bounce and enable kube services

  - name: Reload systemd manager
    command: systemctl daemon-reload
    become: yes
    
  - name: Reload the daemon for the services
    service: 
      name: "{{ item }}"
      enabled: yes
      state: restarted
    become: yes
    with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
      
  - name: Allow Kubernetes API Server to fully initialize
    pause:
      seconds: 15



#-------------------------------------------------------------------------------------------
# RBAC setup
#-------------------------------------------------------------------------------------------


  - name: Copy rbac cluster-role to masters
    copy:
      src: "{{ role_path }}/files/rbac-clusterrole.yaml"
      dest: /home/student/rbac-clusterrole.yaml
    become: yes

  - name: Apply the RBAC rules
    shell: kubectl apply -f rbac-clusterrole.yaml
    args:
      chdir: /home/student
    become: yes    

  - name: Copy the cluster role bind file to the masters
    copy:
      src: "{{ role_path }}/files/rbac-clusterrolebind.yaml"
      dest: /home/student/rbac-clusterrolebind.yaml
    become: yes      

  - name: Bind the clusterrole to the kubernetes user.
    shell: kubectl apply -f rbac-clusterrolebind.yaml
    become: yes
