
- name: Generate a calico installation yaml file
  template:
    src: "{{ role_path }}/templates/calico.yaml.j2" 
    dest: "{{ config_dir }}/calico.yaml"

- name: Deploy the calico rbac file
  copy:
    src: "{{ role_path }}/files/calico-v3.1-rbac.yaml" 
    dest: "{{ config_dir }}/calico-v3.1-rbac.yaml"

- name: Apply calico rbac
  command: kubectl apply -f {{ config_dir }}/calico-v3.1-rbac.yaml 

- name: Apply calico service 
  command: kubectl apply -f {{ config_dir }}/calico.yaml 
