ip:
  master1: 172.16.1.5
  master2: 172.16.1.6
  master3: 172.16.1.7
  node1: 172.16.1.8
  node2: 172.16.1.9
  node3: 172.16.1.10
serviceclusteriprange: 172.16.3.0/24
port:
  etcdclient: 2379
  etcds2s: 2380
hname:
  master1: master-1
  master2: master-2
  master3: master-3
  node1: node-1
  node2: node-2
  node3: node-3
clustercidr: 192.168.0.0/16
countrycsr: US
citycsr: Harrisburg
statecsr: Pennsylvania
oucsr: Kubernetes The Alta3 Way
cncsr:
 cnnode1csr: system:node:node-1
 cnnode2csr: system:node:node-2
 cnnode3csr: system:node:node-3
clusterdns: 172.16.3.10
podcidr: 192.168.1.0/24
tlscertfile:
 node1crtloc: node-1.pem
 node2crtloc: node-2.pem
 node3crtloc: node-3.pem
tlsprivatekeyfile:
 node1pkloc: node-1-key.pem
 node2pkloc: node-2-key.pem
 node3pkloc: node-3-key.pem
k8sconfigdir: /home/student/k8s-config/
k8scertsdir: /home/student/k8s-certs/
